const String supabaseUrl = 'https://himggxyijxdebiglomdr.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbWdneHlpanhkZWJpZ2xvbWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4ODY2NzcsImV4cCI6MjA1MDQ2MjY3N30.fHQkKlizuWk1MtOutlsi1lZgbkdIdQ5TxEO6bM8Oytw';
